jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: |
          apt-get update -qq
          apt-get install build-essential autoconf autoconf-archive libtool-bin gettext pkg-config libmozjs-24-dev libreadline-dev -y
          autoreconf -i
          ./configure
          make && make check
